version: "3.3"
services:
  user_services:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: "mongo:4.2.3"
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - ./mongodbdata:/data/db
